name: CI

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache vendor folder
        id: vendor_cache_id
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-vendor-${{ hashFiles('**/composer.lock') }}

      - name: Composer install
        uses: php-actions/composer@v6

  unit-test:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore vendor folder
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-vendor-${{ hashFiles('**/composer.lock') }}

      - name: Unit Test
        uses: php-actions/phpunit@v2
        with:
          php_extensions: xdebug
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml.dist
          args: --coverage-clover runtime/.phpunit.cache/coverage.xml
        env:
          XDEBUG_MODE: coverage

  security-check:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore vendor folder
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-vendor-${{ hashFiles('**/composer.lock') }}

      - name: Dependencies security check
        uses: symfonycorp/security-checker-action@v2
