name: CI

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@v5

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Unit Test
        uses: php-actions/phpunit@v2
        with:
          php_extensions: xdebug
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml.dist
          args: --coverage-clover runtime/.phpunit.cache/coverage.xml
        env:
          XDEBUG_MODE: coverage

  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        id: cache-db
        with:
          path: ~/.symfony/cache
          key: db
      - name: Dependencies security check
        uses: symfonycorp/security-checker-action@v2
